channels:
  - conda-forge
dependencies:
  - r-base=4.3.2
  - r-tidyverse
  - r-viridis
  - r-ggridges
  - r-ggpubr
  - r-gghalves
  - r-vegan
  - r-reshape2
  - r-raster
  - r-mapproj
  - r-sf
  - r-geodata
  - r-plotly
  - r-igraph
